# Generated by Django 3.2.10 on 2022-11-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20221116_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills'),
        ),
    ]
