# Generated by Django 3.2.10 on 2022-11-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20221117_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactprofile',
            options={'ordering': ['timestamp'], 'verbose_name': 'Contact Profile', 'verbose_name_plural': 'Contact Profiles'},
        ),
        migrations.AddField(
            model_name='skill',
            name='score',
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
    ]
